### ISSUE TITLE
R-44 Exportar a hoja de cálculo ACIN los nuevos campos "Tiene Esquema de protección" y "Año desde el cual tiene esquema" a continuación de liderazgo [1,6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_mujeresindigenas#44]

**Comment by vtamara** [comment]
Implementado con 
https://github.com/pasosdeJesus/sivel2_mujeresindigenas/commit/4c5ea19a2fc2bbfc96cacb2a46f6820a762342c5

**Comment by vtamara** [comment]
Se insertan
![esquema-columnas-au-av](https://user-images.githubusercontent.com/701221/179604607-54cf1d48-a0e2-4596-b6e0-7cd674bf7ef6.png)
 nuevos campos en columnas AU y AV

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2022-07-21 08-02-23](https://user-images.githubusercontent.com/10052756/180220051-41413bb1-c9fc-4dfd-93a6-c342391e3d51.png)
